- package.json
> Revert "Bump rollup-plugin-typescript2 from 0.24.3 to 0.25.1"

- src/misc/onboarding_steps/6.ts
> Correct spelling

- .prettierrc
- src/components/dialogs/hacs-add-repository-dialog.ts
- src/localize/languages/en.json
- src/panels/hacs-store-panel.ts
- src/tools/filter-repositories-by-input.ts
Adds search capabilities to the HACS store panels. ~~As a first version, search is basic - searches only by repository name.~~ Uses the same search function as the Add Repository dialog
Changes:
- Add `ha-search` to `hacs-store-panel`
- Add "No results found" empty state + localization. empty state always takes precedence over no results found state
- Refactor `hacs-store-panel`'s render into 3 separate methods. This is a little bit subjective, but I think components are easier to read like this.
- Add `.prettierrc` file - my editor defaults to single quotes, so I thought this is useful. Let me know what you think and if I should change the print width.
No search:
With search results:
Empty state:
> Add search to sections

- script/gulp/rollup.js
This fixes [this LGTM alert](https://lgtm.com/projects/g/hacs/frontend/snapshot/ee67d519d3bbae437a616528f419641b505bf9d8/files/script/gulp/rollup.js?sort=name&dir=ASC&mode=heatmap#L19).
> Remove unused variable

- src/localize/languages/en.json
I was just a bit annoyed on the missing space in `Releasenotes` so I corrected it.
(my smallest PR change in my history of github)
Also, keep up the great work @ludeeus!
> Correction in english language file

- src/components/hacs-repository-card.ts
I recently added ha-card-border-width to Home Assistant, which lets themes change the width of borders. This makes HACS use it.
> Use ha-card-border-width

- src/localize/languages/en.json
To prevent a grammar error in the following sentence "You have 3 Integrations that requires a restart of Home Assistant, you can do that from the 'Server Controls' section under the configuration part of Home Assistant UI."
> Update en.json to fix small grammar error

- src/tools/markdown/markdown.ts
Github shortens all commit links to the first 7 characters of hash like that:
`https://github.com/hacs/frontend/commit/ecc46f369d8cfb96d33f5cc41e640dfdb4921da7` -> https://github.com/hacs/frontend/commit/ecc46f369d8cfb96d33f5cc41e640dfdb4921da7
This PR adds the same functionality to HACS. This change will affect all components using `markdown.html()`.
Before:
After:
> Shorten markdown github commits links

- src/components/dialogs/hacs-update-dialog.ts
https://github.com/hacs/frontend/commit/32be6ca1e1b6ba8efc885995a134eb5d02d07f9a broke filtering of versions list
current master:
this pr:
> Fix changelogs

- src/components/dialogs/hacs-install-dialog.ts
- src/components/hacs-repository-card.ts
- src/tools/added-to-lovelace.ts
- src/tools/update-lovelace-resources.ts
When a user are in storage mode, HACS injects the resource URL.
Even if /hacsfiles are served without cache, with the resent changes in chrome serviceworkers, they would still need to hard reload the page (often multiple times) to use the new "version" of a card/strategy/other for lovelace.
This changes the format for the resource url from `/hacsfiles/<resource-name>/<filename>.js` to `/hacsfiles/<resource-name>/<filename>.js?hacstag=<repoid><numberified-version>`
CC @thomasloven
> Add hacstag to lovelace resource URL's

- src/tools/markdown/styles.ts
> Remove white background from markdown images

- src/components/dialogs/hacs-repository-info-dialog.ts
- src/localize/languages/en.json
> Improve loading screen for repository info

- src/localize/languages/en.json
The directions given after updating HACS integration that require a restart don't currently match the section header on the Server Controls page. This PR updates the English localization to match the current HA section header.
> Updated 'Pending restart' directions

- src/components/hacs-repository-card.ts
- src/panels/hacs-store-panel.ts
Fixes https://github.com/hacs/integration/issues/2351
This PR changes all uses of "top?.open" to "mainWindow.open" provided by the HA frontend. This allows the links to be opened when HA is embedded in an iFrame.
Note that the links still open in new tabs as intended and do not replace the HACS/HA/Parent content.
Tested with HA 2021.12.4, HACS 1.18.0 & Firefox 95.0.2.
> use mainWindow instead of top to open links

- script/gulp/rollup.js
Entrypoint.js  tries to load the main script using dynamic import and falls back to adding a script tag if this fails.
However, the main script is an es module so a normal script fails on the "toplevel export", as reported by https://github.com/hacs/integration/issues/1764
By setting the module attribute on the script tag the script loads successfully. 
(This is more of an band-aid fix. I assume that there is no good way to pass the main script as module js file directly? )
> Fix entrypoint script tag fallback

- src/tools/markdown/markdown.ts
Detects relative URLs that include special characters, such as those used in the images for [this repo](https://github.com/AnthonMS/my-cards). See https://regexr.com/6gft9 for examples of what is/is not picked up by the new expression.
The new expression is activated by, essentially, by the pattern `any-chars.word`. It will _not_ activate if it detects `://` in the string, as this indicates that an absolute URL is in use.
> Better detection of relative URLs.

- src/components/dialogs/hacs-download-dialog.ts
- src/components/dialogs/hacs-navigate-dialog.ts
- src/components/dialogs/hacs-update-dialog.ts
Closes https://github.com/hacs/integration/issues/2524
> Fix linebreaks

- src/panels/hacs-entry-panel.ts
Potentially too hacky, but I used `56px` since that is the width of the icon plus its margin on the right.
**Before:**
**After:**
Only tested via browser dev tools.
> Remove icon next to add-on entry

- src/components/dialogs/hacs-repository-info-dialog.ts
**Note**: I don't have a HACS dev setup, so only tested via browser dev tools.
The "Open Repository" button is misaligned.
> Fix button alignment issue in repo preview

- src/localize/languages/en.json
- src/panels/hacs-experimental-panel.ts
> Add installed, available and status columns

- src/dashboards/hacs-dashboard.ts
- src/data/about.ts
- src/localize/languages/en.json
- src/tools/documentation.ts
> Add FAB to overview to help with confusion

- src/components/dialogs/hacs-download-dialog.ts
- src/data/repository.ts
- src/data/websocket.ts
Reverts hacs/frontend#684
While this should be removed, its replacement is still pretty new, so it is nice to have as a fallback for a little while.
> Revert "Remove version selector"

- src/components/dialogs/hacs-form-dialog.ts
- src/dashboards/hacs-dashboard.ts
- src/localize/languages/en.json
As there is an issue with checkboxes in overflow menus, this is moving to a dialog instead, which also makes it easier to extend in the future.
> Move filter/columns selectors from overflow to dialog

- src/components/hacs-repository-owerflow-menu.ts
- src/dashboards/hacs-dashboard.ts
- src/data/websocket.ts
- src/localize/languages/en.json
> Add dismiss new to overflow menu

- src/components/dialogs/hacs-download-dialog.ts
- src/components/hacs-repository-owerflow-menu.ts
- src/tools/frontend-resource.ts
Moved to backed in https://github.com/hacs/integration/pull/3758
> Remove resource handling

- src/localize/languages/en.json
- to make it clearer what this does
> rename 'show' to 'show details'

- src/components/hacs-repository-owerflow-menu.ts
- src/dashboards/hacs-dashboard.ts
- src/dashboards/hacs-repository-dashboard.ts
- src/styles/hacs-common-style.ts
Fixes https://github.com/hacs/integration/issues/4022
> Switch overflow menues to ha-menu
