- src/buttons/HacsButtonAddToLovelace.ts
- src/main.ts
- src/misc/AddedToLovelace.ts
- src/misc/LovelaceTypes.ts
- src/misc/RepositoryBannerNote.ts
- src/panels/corePanel.ts
- src/panels/repository.ts
- src/style/hacs-style.ts
- src/types.ts
> AddToLovelace

- src/panels/corePanel.ts
- src/panels/settings.ts
- src/types.ts
> Adds Compact mode

- src/panels/corePanel.ts
- src/panels/repository.ts
- src/types.ts
Name (default) and status with the MVP
> Adds sort options

- src/misc/onboarding_steps/0.ts
- src/misc/onboarding_steps/1.ts
- src/misc/onboarding_steps/2.ts
- src/misc/onboarding_steps/3.ts
- src/misc/onboarding_steps/4.ts
- src/misc/onboarding_steps/5.ts
- src/misc/onboarding_steps/6.ts
> Spelling and grammar

- src/components/dialogs/hacs-add-repository-dialog.ts
Closes https://github.com/hacs/integration/issues/1186
> Hide installed repos from add repository list

- src/components/dialogs/hacs-add-repository-dialog.ts
Fixes https://github.com/hacs/integration/issues/1190
> Fix the + menu for new clients

- src/components/dialogs/hacs-install-dialog.ts
Fixes https://github.com/hacs/integration/issues/1197
> Actually read the value of the selected version

- src/layout/hacs-single-page-layout.ts
- src/panels/hacs-entry-panel.ts
Fixes https://github.com/hacs/integration/issues/1187
> Show hamburger when sidebar is always_hidden

- src/components/dialogs/hacs-add-repository-dialog.ts
- src/panels/hacs-sections.ts
- src/panels/hacs-store-panel.ts
Closes https://github.com/hacs/integration/issues/1189
> Filter repositories by section

- src/components/hacs-chip.ts
- src/components/hacs-repository-card.ts
Closes https://github.com/hacs/integration/issues/1212
> Improvements to hacs-chip

- src/components/hacs-repository-card.ts
- src/components/hacs-tabbed-menu.ts
- src/localize/languages/en.json
- src/panels/hacs-store-panel.ts
https://github.com/hacs/integration/issues/1183
> Sort new repositories like discovered integrations

- src/components/dialogs/hacs-install-dialog.ts
Closes https://github.com/hacs/integration/issues/1213
> Set latest tag as default for installation

- src/components/hacs-repository-card.ts
Closes https://github.com/hacs/integration/issues/1232
> Ignore installed for new repositories.

- src/components/hacs-repository-card.ts
Closes https://github.com/hacs/integration/issues/1218
> Reorder items in repository card menu

- src/components/dialogs/hacs-add-repository-dialog.ts
- src/components/dialogs/hacs-dialog.ts
Closes https://github.com/hacs/integration/issues/1193
> Add infinite scroll to add-repository

- src/components/dialogs/hacs-add-repository-dialog.ts
- src/components/dialogs/hacs-dialog.ts
Closes https://github.com/hacs/integration/issues/1208
> Make search float on top

- src/components/dialogs/hacs-add-repository-dialog.ts
- src/localize/languages/en.json
Closes https://github.com/hacs/integration/issues/1219
> Add sorting filters for add-repository dialog

- src/components/dialogs/hacs-dialog.ts
Closes https://github.com/hacs/integration/issues/1253
> Fix height issue with firefox

- src/components/dialogs/hacs-about-dialog.ts
Fixed a minor typo on about dialog (Asisstant = Assistant)
> Fix minor typo on about dialog

- src/components/hacs-repository-card.ts
- src/data/common.ts
- src/localize/languages/en.json
- src/panels/hacs-entry-panel.ts
- src/panels/hacs-store-panel.ts
- src/tools/added-to-lovelace.ts
- src/tools/get-messages.ts
Closes https://github.com/hacs/integration/issues/1226 
Closes https://github.com/hacs/integration/issues/1262
> Display errors for not loaded, and restart pending

- src/components/dialogs/hacs-add-repository-dialog.ts
- src/components/dialogs/hacs-dialog.ts
- src/components/hacs-checkbox.ts
- src/components/hacs-filter.ts
- src/data/common.ts
- src/panels/hacs-sections.ts
- src/panels/hacs-store-panel.ts
> Adds category filter

- src/components/dialogs/hacs-add-repository-dialog.ts
- src/components/hacs-link.ts
- src/components/hacs-repository-card.ts
- src/components/hacs-tabbed-menu.ts
- src/tools/get-messages.ts
Closes https://github.com/hacs/integration/issues/1267
> Fixes issues with list items on iOS

- src/components/hacs-repository-card.ts
> Fixes display issue when there was multiple active statuses

- src/components/hacs-repository-card.ts
> Fix issue with removing wrong plugin on uninstall

- src/tools/markdown/markdown.ts
> Don't rewrite the URL for markdown files

- src/components/dialogs/hacs-dialog.ts
- src/components/dialogs/hacs-event-dialog.ts
- src/components/dialogs/hacs-removed-dialog.ts
- src/components/hacs-repository-card.ts
- src/components/hacs-section-navigation.ts
- src/data/common.ts
- src/localize/languages/en.json
- src/panels/hacs-entry-panel.ts
- src/styles/hacs-common-style.ts
- src/tools/get-messages.ts
Closes hacs/integration#1342
Fixes hacs/integration#1420
Missing:
> Add more information about removed repositories

- src/styles/element-styles.ts
I have a big screen. The update which made the scrollbar smaller made it very hard to use it. This makes it bigger.
> Make scrollbar bigger

- src/components/dialogs/hacs-add-repository-dialog.ts
> Fix double scrollbar

- package.json
- src/components/dialogs/hacs-about-dialog.ts
- src/components/dialogs/hacs-generic-dialog.ts
- src/components/hacs-link.ts
- yarn.lock
Fixes https://github.com/hacs/integration/issues/1618
> Fix issues in hacs-link

- src/main.ts
closes https://github.com/hacs/integration/issues/1657
> Workaround for chromium 87+ issue

- src/localize/languages/en.json
- src/tools/get-messages.ts
> Change 1 integrations to 1 integration

- src/components/dialogs/hacs-dialog.ts
> Fix max vs min typo

- src/components/dialogs/hacs-about-dialog.ts
- src/components/dialogs/hacs-add-repository-dialog.ts
- src/components/dialogs/hacs-custom-repositories-dialog.ts
- src/components/dialogs/hacs-install-dialog.ts
- src/components/dialogs/hacs-reload-dialog.ts
- src/components/dialogs/hacs-repository-info-dialog.ts
- src/components/dialogs/hacs-update-dialog.ts
- src/components/hacs-filter.ts
- src/components/hacs-repository-card.ts
- src/components/hacs-tabbed-menu.ts
- src/data/hacs.ts
- src/hacs.ts
- src/localize/localize.ts
- src/panels/hacs-entry-panel.ts
- src/panels/hacs-sections.ts
- src/panels/hacs-store-panel.ts
Closes https://github.com/hacs/integration/issues/1765
> Fix localize issues

- src/components/dialogs/hacs-add-repository-dialog.ts
- src/components/dialogs/hacs-dialog.ts
- src/components/dialogs/hacs-repository-info-dialog.ts
- src/panels/hacs-store-panel.ts
Closes https://github.com/hacs/integration/issues/1706
Closes https://github.com/hacs/integration/issues/1449
> Fix display issues with dialogs

- src/tools/get-messages.ts
> Remove message about cache

- src/components/dialogs/hacs-update-dialog.ts
- src/localize/languages/en.json
> Rework update pending dialog

- src/tools/markdown/markdown.ts
> Fix load issue in safari

- src/main.ts
> Force dark

- src/hacs.ts
- src/panels/hacs-sections.ts
- src/tools/get-messages.ts
> Guard for missing configuration

- src/components/hacs-repository-card.ts
- src/panels/hacs-store-panel.ts
Closes https://github.com/hacs/integration/issues/2228
> Use ha-icon-overflow-menu on repository card menu

- src/localize/languages/en.json
- src/panels/hacs-entry-panel.ts
- src/tools/get-messages.ts
Closes https://github.com/hacs/integration/issues/2278
> Add navigate to restart pending message

- src/localize/languages/en.json
Fixes https://github.com/hacs/integration/issues/2287
> Adjust new_repositories_note

- src/components/hacs-repository-card.ts
- src/localize/languages/en.json
Closes https://github.com/hacs/integration/issues/2247
> Allow ignoring configured integrations

- src/components/dialogs/hacs-download-dialog.ts
Closes https://github.com/hacs/integration/issues/2170
> Call repositorySetVersion when selecting version to download

- src/panels/hacs-store-panel.ts
Closes https://github.com/hacs/integration/issues/2485
> Use max-content for clear new button

- src/panels/hacs-entry-panel.ts
Fixes https://github.com/hacs/integration/issues/2576
> Fix padding in update list

- src/components/dialogs/hacs-update-dialog.ts
- src/data/websocket.ts
> Move releasenotes filter to backend

- src/main.ts
> Override custom panel defaults

- src/main.ts
> Handle custom themes

- src/components/dialogs/hacs-dialog-base.ts
> Update dialogs when _repository changes

- src/components/dialogs/hacs-add-repository-dialog.ts
- src/components/hacs-filter.ts
> Make label clickable

- .devcontainer.json
Closes hacs/integration#3020
Done in 87.41s.
> Bump devcontainer

- src/panels/hacs-experimental-panel.ts
closes https://github.com/hacs/integration/issues/3028
> Use radio on mobile

- src/panels/hacs-experimental-panel.ts
Closes https://github.com/hacs/integration/issues/3091
> Always show new repository filter

- src/components/dialogs/hacs-download-dialog.ts
- src/data/repository.ts
- src/data/websocket.ts
> Remove version selector

- src/dashboards/hacs-repository-dashboard.ts
> Fix chip icon color

- src/tools/markdown.ts
> Refactor markdownWithRepositoryContext function to improve URL handling
